CREATE PROCEDURE [dbo].[getClaimantBondCompanyFullAddress] 
	@LicenseNumber int, 
	@ClaimNumber int
AS
BEGIN
	SET NOCOUNT ON;
	EXECUTE (
		'SELECT A.COMPANY_NAME, A.NAME_LINE_1, A.NAME_LINE_2, '+
		'A.ADDRESS_LINE_1, A.ADDRESS_LINE_2, A.CITY, A.STATE, A.POSTAL_CODE '+
		'FROM CLAIMS.BOND_COMPANY A JOIN CLAIMS.BOND B '+
		'ON A.COMPANY_NUMBER=B.COMPANY_NUMBER '+
		'WHERE B.REGISTRATION_NUMBER = ? AND B.CLAIM_NUMBER = ?',
		@LicenseNumber, @ClaimNumber)
	AT ORACLEDB;
END