

CREATE PROCEDURE [dbo].[getLienorNameAddress] 
	@LicenseNumber int, 
	@ClaimNumber int
AS
BEGIN
	SET NOCOUNT ON;
	EXECUTE (
		'SELECT LAST_NAME AS NAME, ADDRESS, CITY, STATE, POSTAL_CODE FROM NAME.V_ALL_CLAIMS_NAMES WHERE ENTITY_TYPE = ? AND REGISTRATION_NUMBER = ? AND CLAIM_NUMBER = ?',
		'LIENR', @LicenseNumber, @ClaimNumber)
	AT ORACLEDB;
END