
CREATE PROCEDURE [dbo].[getRespondentAttyFullAddress] 
	@LicenseNumber int, 
	@ClaimNumber int
AS
BEGIN
	SET NOCOUNT ON;
	EXECUTE (
		'SELECT R_ATTY_ADDRESS, R_ATTY_CITY, R_ATTY_STATE, R_ATTY_ZIP FROM CLAIMS.V_DRS_CORRESPONDENCE WHERE REGISTRATION_NUMBER = ? AND CLAIM_NUMBER = ?',
		@LicenseNumber, @ClaimNumber)
	AT ORACLEDB;
END