
CREATE PROCEDURE [dbo].[preCheckFile] 
	@sectionID  int, 
	@fileNumber int,
	@drsNumber  int = null
AS
SET NOCOUNT ON;
BEGIN
	IF (@sectionID = 7)
		EXECUTE ('SELECT COUNT(*) AS RESULT FROM REGIS.REGISTRATION_STATUS WHERE REGISTRATION_NUMBER = ?',
		@fileNumber) AT ORACLEDB;
	
	IF (@sectionID = 5)
		EXECUTE ('SELECT COUNT(*) AS RESULT FROM ENFORC.INVESTIGATION WHERE INVESTIGATION_NUMBER = ?',
		@fileNumber) AT ORACLEDB;

	IF (@sectionID = 3)
		EXECUTE ('SELECT COUNT(*) AS RESULT FROM CLAIMS.CLAIMS_FILED WHERE REGISTRATION_NUMBER = ? AND CLAIM_NUMBER = ?',
		@fileNumber, @drsNumber) AT ORACLEDB;

END